const plants = [
  {
    name: "Balinis ajeras (Acorus calamus)",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Impedit ipsam nihil fugiat laboriosam aut! Mollitia maiores, incidunt iure facere sed ut? Cupiditate magnam dolores molestias. Voluptas corporis ratione magni et. Lorem ipsum dolor sit, amet consectetur adipisicing elit. Unde molestias excepturi soluta assumenda ut ipsa voluptatibus facere! Veritatis natus aliquid, autem dolorem quo minus, nobis ipsa commodi quidem ratione iusto adipisci tempore ut vero sed eveniet repellendus excepturi odio necessitatibus! Lorem ipsum dolor sit amet consectetur adipisicing elit. Earum molestias libero commodi! Quos, voluptatum minima reiciendis earum est incidunt, voluptates quod rem laudantium nisi natus dolores nam eum rerum voluptas doloremque veniam quis ipsum reprehenderit quasi saepe tenetur in inventore exercitationem? Sed, assumenda voluptatem. Nobis, nesciunt veritatis ipsam dolorum nulla enim ratione. Cum, delectus iste, labore harum fugit recusandae libero in reiciendis, officiis blanditiis facere? Dolores alias a error, numquam, enim exercitationem ducimus nesciunt blanditiis laudantium hic laborum pariatur expedita deleniti eos eaque cupiditate dolorem quod rem quae dignissimos commodi cumque reiciendis, qui odit? Facilis qui officia libero pariatur vel? Lorem ipsum dolor sit amet consectetur adipisicing elit. Exercitationem ipsam quibusdam vitae architecto totam quod fuga culpa facere officia doloribus odio ipsa nemo tempora accusantium voluptates tempore, libero voluptatem saepe atque quo rerum laborum, iste eveniet debitis! Ratione culpa soluta tempore voluptatem adipisci? Non itaque, quos quis porro culpa aperiam.",
    imageName: "ajeras",
  },
  {
    name: "Balinis dobilas (Trifolium rapens)",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Impedit ipsam nihil fugiat laboriosam aut! Mollitia maiores, incidunt iure facere sed ut? Cupiditate magnam dolores molestias. Voluptas corporis ratione magni et. Lorem ipsum dolor sit, amet consectetur adipisicing elit. Unde molestias excepturi soluta assumenda ut ipsa voluptatibus facere! Veritatis natus aliquid, autem dolorem quo minus, nobis ipsa commodi quidem ratione iusto adipisci tempore ut vero sed eveniet repellendus excepturi odio necessitatibus! Lorem ipsum dolor sit amet consectetur adipisicing elit. Earum molestias libero commodi! Quos, voluptatum minima reiciendis earum est incidunt, voluptates quod rem laudantium nisi natus dolores nam eum rerum voluptas doloremque veniam quis ipsum reprehenderit quasi saepe tenetur in inventore exercitationem? Sed, assumenda voluptatem. Nobis, nesciunt veritatis ipsam dolorum nulla enim ratione. Cum, delectus iste, labore harum fugit recusandae libero in reiciendis, officiis blanditiis facere? Dolores alias a error, numquam, enim exercitationem ducimus nesciunt blanditiis laudantium hic laborum pariatur expedita deleniti eos eaque cupiditate dolorem quod rem quae dignissimos commodi cumque reiciendis, qui odit? Facilis qui officia libero pariatur vel? Lorem ipsum dolor sit amet consectetur adipisicing elit. Exercitationem ipsam quibusdam vitae architecto totam quod fuga culpa facere officia doloribus odio ipsa nemo tempora accusantium voluptates tempore, libero voluptatem saepe atque quo rerum laborum, iste eveniet debitis! Ratione culpa soluta tempore voluptatem adipisci? Non itaque, quos quis porro culpa aperiam.",
    imageName: "dobilas",
  },
  {
    name: "Pakalnute (Equisetum)",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Impedit ipsam nihil fugiat laboriosam aut! Mollitia maiores, incidunt iure facere sed ut? Cupiditate magnam dolores molestias. Voluptas corporis ratione magni et. Lorem ipsum dolor sit, amet consectetur adipisicing elit. Unde molestias excepturi soluta assumenda ut ipsa voluptatibus facere! Veritatis natus aliquid, autem dolorem quo minus, nobis ipsa commodi quidem ratione iusto adipisci tempore ut vero sed eveniet repellendus excepturi odio necessitatibus! Lorem ipsum dolor sit amet consectetur adipisicing elit. Earum molestias libero commodi! Quos, voluptatum minima reiciendis earum est incidunt, voluptates quod rem laudantium nisi natus dolores nam eum rerum voluptas doloremque veniam quis ipsum reprehenderit quasi saepe tenetur in inventore exercitationem? Sed, assumenda voluptatem. Nobis, nesciunt veritatis ipsam dolorum nulla enim ratione. Cum, delectus iste, labore harum fugit recusandae libero in reiciendis, officiis blanditiis facere? Dolores alias a error, numquam, enim exercitationem ducimus nesciunt blanditiis laudantium hic laborum pariatur expedita deleniti eos eaque cupiditate dolorem quod rem quae dignissimos commodi cumque reiciendis, qui odit? Facilis qui officia libero pariatur vel? Lorem ipsum dolor sit amet consectetur adipisicing elit. Exercitationem ipsam quibusdam vitae architecto totam quod fuga culpa facere officia doloribus odio ipsa nemo tempora accusantium voluptates tempore, libero voluptatem saepe atque quo rerum laborum, iste eveniet debitis! Ratione culpa soluta tempore voluptatem adipisci? Non itaque, quos quis porro culpa aperiam.",
    imageName: "pakalnute",
  },
  {
    name: "Dilgele (Urtica)",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Impedit ipsam nihil fugiat laboriosam aut! Mollitia maiores, incidunt iure facere sed ut? Cupiditate magnam dolores molestias. Voluptas corporis ratione magni et. Lorem ipsum dolor sit, amet consectetur adipisicing elit. Unde molestias excepturi soluta assumenda ut ipsa voluptatibus facere! Veritatis natus aliquid, autem dolorem quo minus, nobis ipsa commodi quidem ratione iusto adipisci tempore ut vero sed eveniet repellendus excepturi odio necessitatibus! Lorem ipsum dolor sit amet consectetur adipisicing elit. Earum molestias libero commodi! Quos, voluptatum minima reiciendis earum est incidunt, voluptates quod rem laudantium nisi natus dolores nam eum rerum voluptas doloremque veniam quis ipsum reprehenderit quasi saepe tenetur in inventore exercitationem? Sed, assumenda voluptatem. Nobis, nesciunt veritatis ipsam dolorum nulla enim ratione. Cum, delectus iste, labore harum fugit recusandae libero in reiciendis, officiis blanditiis facere? Dolores alias a error, numquam, enim exercitationem ducimus nesciunt blanditiis laudantium hic laborum pariatur expedita deleniti eos eaque cupiditate dolorem quod rem quae dignissimos commodi cumque reiciendis, qui odit? Facilis qui officia libero pariatur vel? Lorem ipsum dolor sit amet consectetur adipisicing elit. Exercitationem ipsam quibusdam vitae architecto totam quod fuga culpa facere officia doloribus odio ipsa nemo tempora accusantium voluptates tempore, libero voluptatem saepe atque quo rerum laborum, iste eveniet debitis! Ratione culpa soluta tempore voluptatem adipisci? Non itaque, quos quis porro culpa aperiam.",
    imageName: "dilgele",
  },
];
export default plants;
